### ISSUE TITLE
Conflicting namespace with User

### ISSUE THREAD

**Issue by Fjalmari** [audienceproject/userreport-ios-sdk#4]
User is really generic class name to have and I bet that most applications are already using it.
The module is called UserReport and the SDK also has class called UserReport so we can't tell which User we want to initialise.

e.g. this can't be done
```swift
UserReport.User() // Type 'UserReport' has no member 'User'
```
and these are failing as well
```swift
User() // Uses our User object
UserReport.configure(sakId: "", mediaId: "", user: User) // Try to use our User object
```

If we can't access the module's namespace, all the generic classes should be reviewed and possibly prefixed. Or make the namespace accessible.

**Comment by pyrtsa** [comment]
Just rephrasing what @Fjalmari said above, this issue concerns in fact two problems in the current SDK:

1. `UserReport`-the-class shadows the name of `UserReport`-the-module, and there's no way to qualify the latter ([this is a known issue in Swift](https://forums.swift.org/t/pitch-fully-qualified-name-syntax/28482)).
2. `User` is arguably too generic a name for what it's used for in `UserReport`, and there's no way to qualify it because of problem 1.

Since the whole SDK is still in a pretty early stage at v0.0.9, I'd **strongly recommend renaming the module** (e.g. `UserReportSDK`) to remove problem 1.

It might also be tasteful to rename `User` into something more specific (`ReportUser`, huh?) but with the module name changed it won't be necessary.

**Comment by hmvs** [comment]
Thank you for bringing this up. We will definitely look into this. Btw, PRs are very welcomed.
